esphome:
  name: htu21d-node-1

esp8266:
  board: esp01_1m

# Enable logging
#logger:

# Enable Home Assistant API
#api:



# configuration entry
mqtt:
  broker: <enter ip address>
  port: 1883
  username: DEMO
  password: Demo@123
  client_id: "ESP_HTU21D_1"
  discovery: true
  topic_prefix: "ESP_HTU21D_1"


ota:
  password: "259f1612312900f8fce74698e5622d4d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Htu21D-Node-1 Fallback Hotspot"
    password: "86OM3KqlqaSb"

captive_portal:

# Example configuration entry for ESP32
i2c:
- id: bus_a
  sda: GPIO2
  scl: GPIO0
  scan: true
  frequency: 100kHz


# Example configuration entry
sensor:
  - platform: htu21d
    address: 0x40
    i2c_id: bus_a
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s